name: Security Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Scan secrets
        uses: gitleaks/gitleaks-action@v2

      - name: HTML lint
        run: npx htmlhint ./public

      - name: Basic header test
        run: |
          echo "Test headers later after deploy"
